In [2]:
import json
import pandas as pd
import os 

os.chdir("/Users/sebastianbahralarcon/Ruben's team Dropbox/blablacar/02_raw_data/03_scrape_trip_details/01_data-raw_json_dumps")

In [24]:
dictionary_trips = {'trip_id': [], 'ratings_list':[]}


for filename in os.listdir(os.getcwd()):
   try:
        with open(os.path.join(os.getcwd(), filename), 'r') as f:
            json_data = json.load(f)

            for trip_dictionary in json_data:
                trip_id = list(trip_dictionary.keys())[0]
                the_trip = trip_dictionary[trip_id]
                rating = the_trip.get('rating')
                ratings_inside = rating[0]
                individual_ratings_list = []
                if rating == None : 
                    individual_ratings_list = None
                else :
                    for global_rating in ratings_inside :
                        individual_rating = rating.get('global_rating')
                        individual_ratings_list.append(individual_rating)
                dictionary_trips['trip_id'].append(trip_id)
                dictionary_trips['ratings_list'].append(individual_ratings_list)
                
   except:
        print(filename) 
        pass

2022-01-14_trips.txt
2022-02-17_trips.txt
2022-02-03_trips.txt
2022-01-21_trips.txt
2022-01-19_trips.txt
2022-02-24_trips.txt
2021-12-31_trips.txt
.DS_Store
2022-01-12_trips.txt
2022-02-05_trips.txt
2022-01-06_trips.txt
2021-12-28_trips.txt
2022-02-08_trips.txt
2022-02-02_trips.txt
2022-01-01_trips.txt
2022-01-15_trips.txt
2022-02-16_trips.txt
2022-02-23_trips.txt
2022-01-20_trips.txt
2022-01-18_trips.txt
2021-12-30_trips.txt
2022-02-04_trips.txt
2022-01-07_trips.txt
2022-01-13_trips.txt
2022-02-10_trips.txt
2022-02-09_trips.txt
2022-01-23_trips.txt
2022-02-15_trips.txt
2022-01-16_trips.txt
2022-01-02_trips.txt
2022-02-01_trips.txt
2022-02-18_trips.txt
2022-01-10_trips.txt
2022-01-04_trips.txt
2022-02-07_trips.txt
2022-01-31_trips.txt
2022-01-09_trips.txt
2022-01-22_trips.txt
2022-01-03_trips.txt
2022-02-14_trips.txt
2022-01-17_trips.txt
2022-02-19_trips.txt
2022-01-05_trips.txt
2022-02-06_trips.txt
2022-01-11_trips.txt
2021-12-26_trips.txt
2022-01-30_trips.txt
2022-01-08_trips.txt

In [20]:
dataframe = pd.DataFrame.from_dict(dictionary_trips)

In [21]:
dataframe

,trip_id,ratings_list
0,2370886041-paris-angers,"[4, 4, 1, 4, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 5, ..."
1,2371478066-belleville-en-beaujolais-la-fleche,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]"
2,2374701076-valenciennes-a84-sortie-40-torigni-...,"[5, 5, 5, 4, 4, 5]"
3,2376867618-nice-montpellier,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
4,2363505921-toulouse-artix,"[5, 5, 5, 5, 5, 5]"
5,2362811122-rennes-orvault,"[5, 4, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, ..."
6,2361753262-cassis-valence,"[5, 5]"
7,2362815249-draveil-amiens,"[5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, ..."
8,2361315252-strasbourg-colmar,"[5, 5, 5, 5]"
9,2363486591-marseille-valence,"[5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 4, 5, 5, 5, 5, ..."
10,2366927216-merignac-toulouse,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 4, 5, 4, 5, ..."
11,2365617516-balma-nimes,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 4, ..."
12,2363837706-lille-paris,"[5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, ..."
13,2363941696-bordeaux-a10-sortie-29-poitiers-nord,[]
14,2363818051-rennes-nantes,"[5, 5, 2, 5, 3, 5, 4, 4, 5, 3, 2, 3, 5, 4, 5, ..."
15,2373687716-allauch-toulon,"[4, 5, 5, 5]"
16,2373729901-lyon-a7-sortie-21-orange-centre,"[4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
17,2373559091-lyon-annecy,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
18,2373344981-plaisir-tours,"[5, 5, 4, 5, 5, 4, 5, 4, 5]"
19,2405221858-antibes-montpellier,"[4, 5, 5, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, ..."
20,2405160638-paris-geneve,"[1, 2]"
21,2378272813-paris-auxerre,[5]
22,2389358478-lyon-montpellier,"[5, 5, 4, 5, 5, 5, 5, 5, 3, 5, 5, 4, 5, 4, 5, ..."
23,2398243438-bordeaux-la-couronne,"[5, 5, 3, 4, 5, 5, 5, 5, 4, 5, 4, 5, 5, 3, 4, ..."
24,2398936558-malakoff-orleans,"[4, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
25,2398462578-nice-aix-en-provence,[]
26,2398889758-cenon-montpellier,"[5, 5]"
27,2398307713-rennes-saint-berthevin,"[5, 4, 4]"
28,2364080556-marignane-montpellier,"[5, 5, 5, 5, 5, 5, 5, 5, 4, 3]"
29,2386116508-aix-en-provence-montpellier,"[5, 5, 4, 5, 4, 4, 5, 5]"
30,2400587188-villeneuve-d-ascq-saint-gibrien,"[4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
31,2400953973-villeurbanne-montpellier,"[5, 5, 5, 5, 4, 5]"
32,2392268843-rennes-nantes,"[5, 5, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, 4, 5, 5, ..."
33,2386518013-argentre-du-plessis-villeneuve-d-ascq,[]
34,2386552258-toulouse-la-rochelle,"[5, 4, 5, 5, 5, 5, 5]"
35,2373867766-gradignan-agen,[]
36,2352783868-jassans-riottier-saint-pierre-des-c...,"[5, 5, 5]"
37,2401942153-merignac-toulouse,[]
38,2401650948-marseille-la-valette-du-var,"[5, 5]"
39,2401514798-montigny-le-bretonneux-clermont-fer...,"[5, 5, 5]"
40,2368215021-lille-chantilly,"[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ..."
41,2359334803-rennes-herouville-saint-clair,"[5, 5, 5, 5, 5, 5, 5, 5]"
42,2359356943-merignac-balma,"[5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 4, 5]"